
import __ASTRO_IMAGE_IMPORT_0 from "./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fcoderhouse-data-analytics%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1 from "./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fcordoba-desempeno%2Findex.md";
import __ASTRO_IMAGE_IMPORT_2 from "./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fcordoba-planificacion%2Findex.md";
import __ASTRO_IMAGE_IMPORT_3 from "./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fcordoba-redaccion%2Findex.md";
import __ASTRO_IMAGE_IMPORT_4 from "./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fgoogle-project-management%2Findex.md";
import __ASTRO_IMAGE_IMPORT_5 from "./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fibm-data-science%2Findex.md";
import __ASTRO_IMAGE_IMPORT_6 from "./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Funilever-supply-chain%2Findex.md";
import __ASTRO_IMAGE_IMPORT_7 from "./estacion.png?astroContentImageFlag=&importer=..%2Fproyectos%2Fgasoductos%2Findex.es.md";
import __ASTRO_IMAGE_IMPORT_8 from "./portada.png?astroContentImageFlag=&importer=..%2Fproyectos%2Fgasoductos%2Findex.es.md";
import __ASTRO_IMAGE_IMPORT_9 from "./traza.png?astroContentImageFlag=&importer=..%2Fproyectos%2Fgasoductos%2Findex.es.md";
export default new Map([["./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fcoderhouse-data-analytics%2Findex.md", __ASTRO_IMAGE_IMPORT_0], ["./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fcordoba-desempeno%2Findex.md", __ASTRO_IMAGE_IMPORT_1], ["./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fcordoba-planificacion%2Findex.md", __ASTRO_IMAGE_IMPORT_2], ["./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fcordoba-redaccion%2Findex.md", __ASTRO_IMAGE_IMPORT_3], ["./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fgoogle-project-management%2Findex.md", __ASTRO_IMAGE_IMPORT_4], ["./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Fibm-data-science%2Findex.md", __ASTRO_IMAGE_IMPORT_5], ["./certificado.jpg?astroContentImageFlag=&importer=..%2Fformacion%2Funilever-supply-chain%2Findex.md", __ASTRO_IMAGE_IMPORT_6], ["./estacion.png?astroContentImageFlag=&importer=..%2Fproyectos%2Fgasoductos%2Findex.es.md", __ASTRO_IMAGE_IMPORT_7], ["./portada.png?astroContentImageFlag=&importer=..%2Fproyectos%2Fgasoductos%2Findex.es.md", __ASTRO_IMAGE_IMPORT_8], ["./traza.png?astroContentImageFlag=&importer=..%2Fproyectos%2Fgasoductos%2Findex.es.md", __ASTRO_IMAGE_IMPORT_9]]);
		